### PR TITLE
add debug cruft for test failure

### PR DESCRIPTION
**Pull request by mattip**

### CODE REVIEW

**Comment by mattip** [comment]
@matthiasdiener the ppc64le run is failing to install libunwind-devel on centos7. Does it exist? It seems previously we were using debian which provides the library.

**Comment by mattip** [comment]
[Here](https://app.travis-ci.com/github/vmprof/vmprof-python/jobs/558655487#L319) is the failure, which I can reproduce locally after enabling :
```
$ docker run -it --rm  -v/usr/bin/qemu-ppc64le-static:/usr/bin/qemu-ppc64le-static quay.io/pypa/manylinux2014_ppc64le:2021-10-06-94da8f1
# yum search unwind
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: ftp.bme.hu
 * centos-sclo-rh: ftp.bme.hu
 * extras: ftp.bme.hu
 * updates: ftp.bme.hu
base                                                                                                                                     | 3.6 kB  00:00:00     
centos-sclo-rh                                                                                                                           | 3.0 kB  00:00:00     
extras                                                                                                                                   | 2.9 kB  00:00:00     
updates                                                                                                                                  | 2.9 kB  00:00:00     
(1/5): extras/7/ppc64le/primary_db                                                                                                       | 223 kB  00:00:01     
(2/5): base/7/ppc64le/group_gz                                                                                                           | 153 kB  00:00:05     
(3/5): centos-sclo-rh/ppc64le/primary_db                                                                                                 | 2.4 MB  00:00:06     
(4/5): updates/7/ppc64le/primary_db                                                                                                      | 9.7 MB  00:00:07     
(5/5): base/7/ppc64le/primary_db                                                                                                         | 4.8 MB  00:00:08     
Warning: No matches found for: unwind
No matches found

```

**Comment by matthiasdiener** [comment]
Indeed, CentOS7/ppc64le seems to lack libunwind packages. I found these somewhat older versions for ppc64le here: https://cbs.centos.org/koji/buildinfo?buildID=7176 . I confirmed that vmprof builds fine with them. They can be installed as follows:

```
$ yum install -y https://cbs.centos.org/kojifiles/packages/libunwind/1.1/10.el7/ppc64le/libunwind-1.1-10.el7.ppc64le.rpm
$ yum install -y https://cbs.centos.org/kojifiles/packages/libunwind/1.1/10.el7/ppc64le/libunwind-devel-1.1-10.el7.ppc64le.rpm
```

Another option might be the conda-forge libunwind package.

**Comment by mattip** [comment]
I went with downloading and building libunwind from source. But now there is a segfault when testing with ppc64le https://app.travis-ci.com/github/vmprof/vmprof-python/jobs/558876840#L1689

**Comment by mattip** [comment]
Hmm. There is one on x86_64 as well https://github.com/vmprof/vmprof-python/runs/5116198518?check_suite_focus=true#step:3:590

**Comment by mattip** [comment]
Closing, tests are now passing

**Pull request closed without merging**
