### PR TITLE
Support flamegraph output

### PR DESCRIPTION
**Pull request by methane**
usage: vmprof-flamegraph profile.out | flamegraph.pl > profile.svg

### CODE REVIEW

**Comment by methane** [comment]
Should I add `--format=pretty` option to `vmprofshow` command instead of adding new command?

**Comment by fijal** [comment]
I don't use vmprofshow - I use the web interface, so I don't care

**Comment by methane** [comment]
@fijal Should I release separated package?

**Comment by fijal** [comment]
Hi Inada.

Did you release a separate pypi package? If so maybe we can link it from the website

**Comment by methane** [comment]
Not yet.  Standalone script is here.
https://github.com/methane/vmprof-flamegraph

I'll release it when I write README and setup script.

**Comment by fijal** [comment]
Feel free to issue a pull request updating the docs.

**Pull request closed without merging**
