### PR TITLE
make sure it works on pypy 5.8

### PR DESCRIPTION
**Pull request by antocuni**
this fixes it for now. But I wonder whether we should switch to a more robust way of specifying options: e.g., we could pass them in a dictionary and then the backend can ignore the ones if doesn't know about (and in that case we also need a way to *know* which are the options the backend knows about, to be able to emit the correct warnings)

### CODE REVIEW

**Comment by mattip** [comment]
After this pull request ``vmprof.disable()`` hangs while running CPU at 100% on PyPY HEAD.
To reproduce:

```
pypy-latest/bin/pip install git+https://github.com/vmprof/vmprof-python.git@master
pypy-latest/bin/pypy
```

```
>>>> import vmprof, tempfile
>>>> fileno, path = tempfile.mkstemp(prefix="vmprof", suffix=".output")
>>>> vmprof.enable(fileno)
>>>> vmprof.disable() #never returns
```

**Comment by mattip** [comment]
pypy built with lldebug does not hang :(. Is there an uninitialized variable somewhere?

**Comment by mattip** [comment]
fwiw, the hang seems to be in ``vmp_scan_profile``, looking at the code there is a ``while(1)`` in that function. Did it change over the last few commits?

**Comment by mattip** [comment]
it seems to be some kind of interaction between LTO and vmprof, specifically the ``read()`` call in ``_skip_string()`` which is called from the ``MARKER_META`` case in the switch statement in ``vmp_scan_profile``. When compiled with ``-flto`` that read consistently hangs, when compiled without lto the test program runs to completion

**Comment by mattip** [comment]
breaking into gdb when that occurs, there is a JMP to the current address, i.e. an infinite tight loop
 http://imgur.com/a/Wkl74

**Comment by planrich** [comment]
Wow, thanks for digging into that. That is a bit odd, why does LTO optimize the code in such a way that an infinite loop is created? I'm also investigating.

**Comment by mattip** [comment]
-flto is a now a translation time option, defaulting to False.
However, now this commit does not work, it should be

        if pypy_version_info > (5, 8, 0):
            _vmprof.enable(gz_fileno, period, memory, lines, native, real_time)
        elif pypy_version_info == (5, 8, 0):
            _vmprof.enable(gz_fileno, period, memory, lines, native)
        else:
            _vmprof.enable(gz_fileno, period) # , memory, lines, native)

**Comment by planrich** [comment]
yes sorry. I'm currently fighting the build bots. The C code that 'probably' cause this issue now does not exist anymore. It is now written in python and integrated in the profile reader.

**Pull request merged**
