### PR TITLE
Add six depency. Fixes #84

### LINKED ISSUE #84: pip install vmprof does not install six depecy
```bash
Traceback (most recent call last):
  File "C:\Miniconda2\envs\test-vmprof\lib\runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "C:\Miniconda2\envs\test-vmprof\lib\runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "C:\Miniconda2\envs\test-vmprof\lib\site-packages\vmprof\__init__.py", line 4, in <module>
    from . import cli
  File "C:\Miniconda2\envs\test-vmprof\lib\site-packages\vmprof\cli.py", line 4, in <module>
    from six.moves import configparser
ImportError: No module named six.moves
```

### LINKED ISSUE #85: vmprof generates malfunction output with 64 bit Python in Windows
Synopsis:

```
>python -m vmprof -o prof-x64.log sometest.py

>python -m vmprof.upload prof-x64.log
Traceback (most recent call last):
  File "C:\Python27_x64\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27_x64\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27_x64\lib\site-packages\vmprof\upload.py", line 105, in <module>
    main()
  File "C:\Python27_x64\lib\site-packages\vmprof\upload.py", line 94, in main
    stats = vmprof.read_profile(args.profile)
  File "C:\Python27_x64\lib\site-packages\vmprof\profiler.py", line 34, in read_profile
    period, profiles, virtual_symbols, interp_name = read_prof(prof_file)
  File "C:\Python27_x64\lib\site-packages\vmprof\reader.py", line 172, in read_prof
    assert read_word(fileobj) == 0 # header count
  File "C:\Python27_x64\lib\site-packages\vmprof\binary.py", line 19, in read_word
    r = int(struct.unpack('l', b)[0])
struct.error: unpack requires a string argument of length 4

>python -V
Python 2.7.12

>python -c "import sys; print(sys.version)"
2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
```

It works with x86 Python:

```
>python -m vmprof -o prof-x86.log sometest.py

>python -m vmprof.upload prof-x86.log
Compiling and uploading to http://vmprof.com...
VMProf log: http://vmprof.com/#/e6881666e8da424f33b18ecfd767d708

C:\Working\Repositories>python -V
Python 2.7.12

C:\Working\Repositories>python -c "import sys; print(sys.version)"
2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
```

```
>python -m vmprof.upload prof-x64.log
Traceback (most recent call last):
  File "C:\Python27_x86\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27_x86\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27_x86\lib\site-packages\vmprof\upload.py", line 105, in <module>
    main()
  File "C:\Python27_x86\lib\site-packages\vmprof\upload.py", line 94, in main
    stats = vmprof.read_profile(args.profile)
  File "C:\Python27_x86\lib\site-packages\vmprof\profiler.py", line 34, in read_profile
    period, profiles, virtual_symbols, interp_name = read_prof(prof_file)
  File "C:\Python27_x86\lib\site-packages\vmprof\reader.py", line 231, in read_prof
    assert not marker, (fileobj.tell(), repr(marker))
AssertionError: (69L, "'0'")
```

The content of `sometest.py`:

``` python
import time

for _ in xrange(1000):
    time.sleep(.001)
```

Feel free to ask for additional information which can help to resolve this issue. Thanks!

### PR DESCRIPTION
**Pull request by Kojoley**
Fixes #84

### CODE REVIEW

**Comment by Kojoley** [comment]
Sorry for this confusion with issue numbers :pensive:

**Comment by planrich** [comment]
Thanks for the pull request.

**Comment by Kojoley** [comment]
FYI: I do not know why, but `six` was removed from dependencies in https://github.com/vmprof/vmprof-python/commit/6f777cce9734ff49779dd54ea0af65588892263c.

**Comment by planrich** [comment]
At that time I thought that six was not needed anymore because I removed the usage urllib. But six is used some place else. That was my bad. Thx for fixing it.

**Pull request merged**
