### PR TITLE
PPC64: add native profiling support

### PR DESCRIPTION
**Pull request by matthiasdiener**
~~TODO:~~
~~- [x] add to Travis CI~~

### CODE REVIEW

**Comment by matthiasdiener** [comment]
This is ready for review @mattip @fijal. I can't see whether it is building on Travis, but it works fine on my ppc64le machine.

**Comment by mattip** [comment]
It turns out this repo was building with travis-ci.org, which has shut down. We should have migrated to travis-ci.com. I am doing it now.

**Comment by mattip** [comment]
close/reopen to trigger travis-ci.com

**Comment by mattip** [comment]
close/reopen to trigger travis-ci.com

**Comment by mattip** [comment]
@matthiasdiener can you push an empty commit to hopefully trigger CI `git commit -m "trigger CI" --allow-empty; git push`

**Comment by mattip** [comment]
hmm, maybe it will only trigger on new PRs?

**Comment by matthiasdiener** [comment]
> hmm, maybe it will only trigger on new PRs?

I opened #239 to test this but it seems to make no difference :-(

**Pull request closed without merging**
