### PR TITLE
Add start and end time to profile, with timezone

### PR DESCRIPTION
**Pull request by jonashaag**
@planrich 

Not sure if I got all the C-level timestamp/timezone stuff correct.

### CODE REVIEW

**Comment by planrich** [comment]
I have reviewed it. I pulled it into the branch vmmemory. It is now passing tests and I have added one to ensure the timestamp data is correctly logged.

**Comment by planrich** [comment]
I was too fast. We of course need a Windows implementation. Do you feel like adding that?

**Comment by jonashaag** [comment]
Sure

**Comment by jonashaag** [comment]
So, this works now, with the caveat that it doesn't support time zones because I couldn't figure out how to do it. Windows has weird time zones.

Maybe we should get timezone information in Python instead, where that's trivial.

Also it seems like it can't build in the Appveyor environment because of an older version of VC++ which misses `stdint.h`. Not sure if we can do without that file.

**Comment by planrich** [comment]
Thanks I have copied the windows implementation to the vmmemory branch. Thanks

**Pull request closed without merging**
