### PR TITLE
Add --input opiton to cli

### PR DESCRIPTION
**Pull request by methane**
I want to show or upload existing file.

### CODE REVIEW

**Comment by fijal** [comment]
I would prefer this to be a completely separate program (please document it too)

**Comment by methane** [comment]
How about `python -m vmprof.show` and `python -m vmprof.send` ?

**Comment by fijal** [comment]
sounds awkward, maybe really a program that installs in bin/?

**Comment by methane** [comment]
Which do you prefer?
`vmprof-show` and `vmprof-send`?
or
`vmprof profile program [args...], `vmprof show prof.data` and `vmprof send prof.data`?

**Comment by fijal** [comment]
vmprof show (but maybe a different name, like vmprofcli not to confuse with the package name?)

**Comment by methane** [comment]
I see.
I'll try to make it later.

**Comment by methane** [comment]
@fijal After thinking about design, I want to make `vmprof` command equals to
`python -m vmprof`, like `pip` and `python -m pip`.
How do you feel about it?

**Comment by fijal** [comment]
I'm probably indifferent

**Comment by methane** [comment]
Close since there is `vmprofshow` now.

**Pull request closed without merging**
